"""Add habit tracker fields to User model

Revision ID: 57e357d0b5f3
Revises: 3b1802fd944f
Create Date: 2025-10-09 06:59:46.845479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57e357d0b5f3'
down_revision = '3b1802fd944f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habit_daily_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('habit_completed_tasks', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('habit_last_reset', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('habit_streak_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('habit_game_states', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('habit_game_states')
        batch_op.drop_column('habit_streak_days')
        batch_op.drop_column('habit_last_reset')
        batch_op.drop_column('habit_completed_tasks')
        batch_op.drop_column('habit_daily_points')

    # ### end Alembic commands ###
