"""Add username as nullable field

Revision ID: 89503c0f6e8a
Revises: 57e357d0b5f3
Create Date: 2025-10-11 17:53:21.256528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89503c0f6e8a'
down_revision = '57e357d0b5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_login')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
